// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyPatch(arg1:string,arg2:boolean):Promise<main.ActionResult>;

export function GetInitialState():Promise<main.AppState>;

export function LaunchAntigravity(arg1:string):Promise<main.ActionResult>;

export function RefreshStatus(arg1:string):Promise<main.AppState>;

export function RestoreOriginal(arg1:string,arg2:boolean):Promise<main.ActionResult>;

export function SelectAsarFile():Promise<string>;
