// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPatch(arg1, arg2) {
  return window['go']['main']['App']['ApplyPatch'](arg1, arg2);
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function LaunchAntigravity(arg1) {
  return window['go']['main']['App']['LaunchAntigravity'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RefreshStatus(arg1) {
  return window['go']['main']['App']['RefreshStatus'](arg1);
}

export function RestoreOriginal(arg1, arg2) {
  return window['go']['main']['App']['RestoreOriginal'](arg1, arg2);
}

export function SelectAsarFile() {
  return window['go']['main']['App']['SelectAsarFile']();
}
